name: ServerPlugins
version: 0.5
api-version: 1.15
author: LavXo
description: Some minecraft plungins.

main: me.server.plugins.Main

commands:
  clear:
    description: Fajna komenda. A czysci hipkom chat.
    permission: chat.clear
    default: op
  cc:
    description: Fajna komenda. A czysci hipkom chat.
    permission: chat.clear
    default: op
  curios:
    description: curios
    permission: chat.clear
    default: op
  wizzard:
    description: Daje fajnom ruszczke.
    permission: tools.addlightningwand
    default: op
  fly:
    description: Daje latanko.
    permission: chat.clear
    default: op